### ISSUE TITLE
Mainframer path for configurations

### ISSUE THREAD

**Issue by ming13** [elpassion/mainframer-intellij-plugin#134] opened 2017-03-21 11:46 UTC
1. Run → Edit Configurations
2. Choose a configuration.
3. Change a Mainframer Make step.

Currently there is a Mainframer path option. I think it can be kind of useless, usually there is a single Mainframer per project. What do you think?

**Comment by pavlospt** [comment] 2017-03-28 11:09
Agree on that, I also get an error that the plugin can not find Mainframer, even though it exists and I can select it!

**Comment by jozzi05** [comment] 2017-03-30 22:03
@ming13 as you said usually there is a single Mainframer per project, but there may be a case when someone will be in need to use this additional configuration. We don't want to take away from the user this possibility, especially when path is set from the beginning to the default one.

**Comment by jozzi05** [comment] 2017-03-30 22:14
@pavlospt could you please provide more information?  I can't reproduce it, so maybe this problem is currently fixed. 

We are going to release 1.0 version soon, but we have to wait for @ghostbuster91 who is currently on vacation. So please be patient.

**Comment by pawegio** [comment] 2017-03-31 08:11
@pavlospt which *Mainframer Integration* plugin version are you using?

**Comment by pavlospt** [comment] 2017-03-31 08:42
@jozzi05 Yeap, that's what I thought because I couldn't explain it when searching the source code. @pawegio I am on 0.3.3 so I guess it has been already fixed!

**Comment by ming13** [comment] 2017-04-04 19:46
@jozzi05 Well, this is arguable of course :-) I see little benefit in this since extra Mainframer instance requires script copy and a separate config directory. Maybe it makes more sense for web projects or something like that, so I see your point.

**Closed** 2017-04-21 12:38 UTC
Labels: wontfix
